elide:
  modelPackage: 'com.spiashko.elidedemo.models'
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  swagger:
    path: /doc
    enabled: true
    version: "1.0"

spring:
  application:
    name: Elide
  jpa:
    hibernate:
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      ddl-auto: 'validate'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: ''
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
server:
  port: 8080

logging:
  path: /tmp

---

spring:
  profiles: production
  jpa:
    hibernate:
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      ddl-auto: 'validate'
    properties:
      hibernate.dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.jdbc.fetch_size: 50
      hibernate.default_batch_fetch_size: 100
      hibernate.generate_statistics: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/elide_demo_db
    username: elide_demo_user
    password: elide_demo_pass
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
server:
  port: 8080


